# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COrderDetail',
            fields=[
                ('odno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pquat', models.IntegerField()),
                ('remainder', models.IntegerField()),
                ('subAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=40)),
                ('caddr', models.CharField(max_length=40)),
                ('consignee', models.CharField(max_length=20)),
                ('conAddr', models.CharField(max_length=40)),
                ('ctel', models.CharField(max_length=11)),
                ('cemail', models.CharField(max_length=40, null=True)),
                ('credit', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Ordinary'), ('D', 'Bad')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('ono', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('odate', models.DateField()),
                ('deliveryDate', models.DateField()),
                ('amount', models.FloatField()),
                ('ostatus', models.CharField(choices=[('0', 'Unhandled'), ('1', 'Handled but insufficient'), ('2', 'Completely handled')], default='0', max_length=1)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPrompt',
            fields=[
                ('cpromptno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('freight', models.FloatField()),
                ('cpdate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('creceiptno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('crdate', models.DateField()),
                ('cpromptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.CustomerPrompt')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
                ('ddesc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('dcno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dcDesc', models.CharField(max_length=100)),
                ('dcRate', models.FloatField(default=0.0)),
                ('dcAbs', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchBill',
            fields=[
                ('dbno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dbdate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('fid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=40)),
                ('faddr', models.CharField(max_length=40, null=True)),
                ('ftel', models.CharField(max_length=11)),
                ('femail', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('occupiedQuat', models.IntegerField(default=0)),
                ('dailyDemand', models.IntegerField()),
                ('setupCost', models.FloatField()),
                ('holdingCost', models.FloatField()),
                ('leadTime', models.FloatField()),
                ('shortagecost', models.FloatField()),
                ('isp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMgmt',
            fields=[
                ('mgmtno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mgmtDesc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('gauge', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.FloatField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Factory')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingOrder',
            fields=[
                ('pono', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('podate', models.DateField()),
                ('deliveryDate', models.DateField()),
                ('amount', models.FloatField()),
                ('postatus', models.CharField(choices=[('0', 'Undelivered'), ('1', 'Delivered but insufficient'), ('2', 'Completely delivered')], max_length=1)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingOrderDetail',
            fields=[
                ('podno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pquant', models.IntegerField()),
                ('remainder', models.IntegerField()),
                ('price', models.FloatField()),
                ('subAmount', models.FloatField()),
                ('dcno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Discount')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Product')),
                ('pono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.PurchasingOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('rno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rdate', models.DateField()),
                ('rstatus', models.CharField(choices=[('0', 'Not replenished'), ('1', 'Replenished')], default='0', max_length=1)),
                ('pono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.PurchasingOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ReplenishmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdno', models.CharField(max_length=10)),
                ('quat', models.IntegerField()),
                ('rdStatus', models.CharField(choices=[('0', 'Unchecked'), ('1', 'Qualified'), ('2', 'Unqualified')], default='0', max_length=1)),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Product')),
                ('podno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.PurchasingOrderDetail')),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Replenishment')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('authDesc', models.CharField(max_length=100, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Department')),
            ],
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('invtLevel', models.CharField(choices=[('0', 'Sufficiency'), ('1', 'ROP'), ('2', 'Danger'), ('3', 'Shortage')], max_length=1, primary_key=True, serialize=False)),
                ('levelRate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockUp',
            fields=[
                ('suno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sudate', models.DateField()),
                ('suStatus', models.CharField(choices=[('0', 'Undelivered'), ('1', 'Delivered')], default='0', max_length=1)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Customer')),
                ('ono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.CustomerOrder')),
            ],
        ),
        migrations.CreateModel(
            name='StockUpDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudno', models.CharField(max_length=10)),
                ('quat', models.IntegerField()),
                ('sudStatus', models.CharField(choices=[('0', 'Sufficient'), ('1', 'Insufficient'), ('2', 'Stock out')], max_length=1)),
                ('odno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.COrderDetail')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Product')),
                ('suno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.StockUp')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPrompt',
            fields=[
                ('spromptno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('freight', models.FloatField()),
                ('spdate', models.DateField()),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Replenishment')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierReceipt',
            fields=[
                ('sreceiptno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('srdate', models.DateField()),
                ('spromptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.SupplierPrompt')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsys.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('wno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('waddr', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='stockupdetail',
            name='wno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Warehouse'),
        ),
        migrations.AddField(
            model_name='replenishmentdetail',
            name='wno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.StockLevel'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='mgmtno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.InventoryMgmt'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='wno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Warehouse'),
        ),
        migrations.AddField(
            model_name='dispatchbill',
            name='suno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.StockUp'),
        ),
        migrations.AddField(
            model_name='customerprompt',
            name='suno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.StockUp'),
        ),
        migrations.AddField(
            model_name='corderdetail',
            name='dcno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Discount'),
        ),
        migrations.AddField(
            model_name='corderdetail',
            name='ono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.CustomerOrder'),
        ),
        migrations.AddField(
            model_name='corderdetail',
            name='pno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='stockupdetail',
            unique_together=set([('suno', 'sudno')]),
        ),
        migrations.AlterUniqueTogether(
            name='replenishmentdetail',
            unique_together=set([('rno', 'rdno')]),
        ),
        migrations.AlterUniqueTogether(
            name='productcatalog',
            unique_together=set([('fid', 'pno')]),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('pno', 'wno')]),
        ),
    ]
