# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iatype', models.CharField(choices=[('-1', 'Out'), ('1', 'In')], max_length=1)),
                ('quantity', models.IntegerField()),
                ('iadate', models.DateField()),
                ('billReference', models.DateField(max_length=10)),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Product')),
                ('wno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('srno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('srdate', models.DateField()),
                ('srstatus', models.CharField(choices=[('0', 'Incompleted'), ('1', 'Completed')], default='0', max_length=1)),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.Replenishment')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnDetail',
            fields=[
                ('srdno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rdno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.ReplenishmentDetail')),
                ('srno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.SalesReturn')),
            ],
        ),
    ]
