# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0002_inventoryaccount_salesreturn_salesreturndetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaccount',
            name='billReference',
            field=models.CharField(max_length=10),
        ),
    ]
