# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0004_auto_20171227_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaccount',
            name='iatype',
            field=models.CharField(choices=[('-1', 'Out'), ('1', 'In')], max_length=2),
        ),
    ]
