# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0005_auto_20171228_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprompt',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprompt',
            name='cpstatus',
            field=models.CharField(choices=[('0', 'Unreceived'), ('1', 'Received')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='supplierprompt',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierprompt',
            name='spstatus',
            field=models.CharField(choices=[('0', 'Unpaid'), ('1', 'Paid')], default='0', max_length=1),
        ),
    ]
