# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0007_auto_20180103_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='demandStd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
